# Use a base image with OpenJDK 17 and JAR packaging support
FROM openjdk

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file generated by Spring Boot build to the container's working directory
COPY target/demo-0.0.1-SNAPSHOT.jar .

EXPOSE 3305

# Specify the command to run your Spring Boot application
CMD ["java", "-jar", "demo-0.0.1-SNAPSHOT.jar"]
